name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: myenv
          environment-file: environment.yml
          python-version: 3.11
          use-only-tar-bz2: true
      - name: Test with pytest
        shell: bash -l {0}
        run: |
          pytest
